apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-pod
  labels:
    first: app
spec: # Behaviour of the replicaset
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: # behaviour fo the pod
      containers:
         - name: fitness-container
           image: parmith/fit:v1.0.0

           ports:
             - containerPort: 5000

apiVersion: v1
kind: Service
metadata:
  name: parmith-service
spec:
  selector:
    app: web
  ports:
   - protocol: TCP
     port: 5000
     targetPort: 5000
  type: NodePort